name: 'Read adobe.json version'
description: 'Output version numbers with adobe.json'
inputs:
  path:
    description: 'Path of adobe.json'
    default: "./"
outputs:
  version:
    description: "Version of package"
runs:
  using: 'node12'
  main: 'lib/main.js'
